
import React, { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Code } from 'lucide-react';
import { toast } from 'sonner';
import { copyToClipboard } from '@/utils/randomUtils';

export const MetaTagGenerator = () => {
  const [title, setTitle] = useState<string>('');
  const [description, setDescription] = useState<string>('');
  const [keywords, setKeywords] = useState<string>('');
  const [url, setUrl] = useState<string>('');
  const [author, setAuthor] = useState<string>('');
  const [metaTagsOutput, setMetaTagsOutput] = useState<string>('');

  const generateMetaTags = () => {
    let metaTags = `<!-- Meta Tags Generated by SEO Tool -->\n`;
    metaTags += `<title>${title}</title>\n`;
    
    if (description) {
      metaTags += `<meta name="description" content="${description}" />\n`;
    }
    
    if (keywords) {
      metaTags += `<meta name="keywords" content="${keywords}" />\n`;
    }
    
    if (author) {
      metaTags += `<meta name="author" content="${author}" />\n`;
    }
    
    metaTags += `<meta property="og:title" content="${title}" />\n`;
    
    if (description) {
      metaTags += `<meta property="og:description" content="${description}" />\n`;
    }
    
    if (url) {
      metaTags += `<meta property="og:url" content="${url}" />\n`;
    }
    
    metaTags += `<meta name="twitter:card" content="summary_large_image" />\n`;
    metaTags += `<meta name="twitter:title" content="${title}" />\n`;
    
    if (description) {
      metaTags += `<meta name="twitter:description" content="${description}" />\n`;
    }
    
    metaTags += `<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n`;
    
    setMetaTagsOutput(metaTags);
    toast.success("متا تگ‌ها با موفقیت ایجاد شدند");
  };

  return (
    <Card>
      <CardContent className="p-6 space-y-4">
        <div className="space-y-2">
          <Input
            placeholder="عنوان صفحه"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <Textarea
            placeholder="توضیحات متا"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
          <Input
            placeholder="کلمات کلیدی (با کاما جدا کنید)"
            value={keywords}
            onChange={(e) => setKeywords(e.target.value)}
          />
          <Input
            placeholder="آدرس URL"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
          />
          <Input
            placeholder="نویسنده"
            value={author}
            onChange={(e) => setAuthor(e.target.value)}
          />
          <Button 
            onClick={generateMetaTags}
            className="w-full"
          >
            <Code className="mr-2" size={18} />
            تولید متا تگ‌ها
          </Button>
        </div>
        
        {metaTagsOutput && (
          <div 
            className="p-4 bg-muted rounded-lg cursor-pointer font-mono text-sm whitespace-pre-wrap dir-ltr"
            onClick={() => copyToClipboard(metaTagsOutput)}
          >
            {metaTagsOutput}
          </div>
        )}
      </CardContent>
    </Card>
  );
};
