
import React, { useState } from 'react';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Code } from 'lucide-react';
import { toast } from 'sonner';
import { copyToClipboard } from '@/utils/randomUtils';

export const RobotsTxtGenerator = () => {
  const [userAgent, setUserAgent] = useState<string>('*');
  const [allowPaths, setAllowPaths] = useState<string>('/');
  const [disallowPaths, setDisallowPaths] = useState<string>('');
  const [sitemapUrl, setSitemapUrl] = useState<string>('');
  const [robotsTxtOutput, setRobotsTxtOutput] = useState<string>('');

  const generateRobotsTxt = () => {
    let robotsTxt = `# robots.txt generated by SEO Tool\n\n`;
    robotsTxt += `User-agent: ${userAgent}\n`;
    
    if (allowPaths) {
      const paths = allowPaths.split('\n');
      paths.forEach(path => {
        if (path.trim()) {
          robotsTxt += `Allow: ${path.trim()}\n`;
        }
      });
    }
    
    if (disallowPaths) {
      const paths = disallowPaths.split('\n');
      paths.forEach(path => {
        if (path.trim()) {
          robotsTxt += `Disallow: ${path.trim()}\n`;
        }
      });
    }
    
    if (sitemapUrl) {
      robotsTxt += `\nSitemap: ${sitemapUrl}\n`;
    }
    
    setRobotsTxtOutput(robotsTxt);
    toast.success("فایل robots.txt با موفقیت ایجاد شد");
  };

  return (
    <Card>
      <CardContent className="p-6 space-y-4">
        <div className="space-y-2">
          <Select value={userAgent} onValueChange={setUserAgent}>
            <SelectTrigger>
              <SelectValue placeholder="User-agent" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="*">همه روبات‌ها (*)</SelectItem>
              <SelectItem value="Googlebot">Googlebot</SelectItem>
              <SelectItem value="Bingbot">Bingbot</SelectItem>
              <SelectItem value="Baiduspider">Baiduspider</SelectItem>
              <SelectItem value="YandexBot">YandexBot</SelectItem>
            </SelectContent>
          </Select>
          
          <Textarea
            placeholder="مسیرهای مجاز (هر مسیر در یک خط)"
            value={allowPaths}
            onChange={(e) => setAllowPaths(e.target.value)}
          />
          
          <Textarea
            placeholder="مسیرهای غیر مجاز (هر مسیر در یک خط)"
            value={disallowPaths}
            onChange={(e) => setDisallowPaths(e.target.value)}
          />
          
          <Input
            placeholder="آدرس نقشه سایت (Sitemap)"
            value={sitemapUrl}
            onChange={(e) => setSitemapUrl(e.target.value)}
          />
          
          <Button 
            onClick={generateRobotsTxt}
            className="w-full"
          >
            <Code className="mr-2" size={18} />
            تولید robots.txt
          </Button>
        </div>
        
        {robotsTxtOutput && (
          <div 
            className="p-4 bg-muted rounded-lg cursor-pointer font-mono text-sm whitespace-pre-wrap dir-ltr"
            onClick={() => copyToClipboard(robotsTxtOutput)}
          >
            {robotsTxtOutput}
          </div>
        )}
      </CardContent>
    </Card>
  );
};
