
export const finglishWordDatabase: Record<string, string> = {
  // Common greetings and phrases
  'salam': 'سلام',
  'khodafez': 'خداحافظ',
  'bedroud': 'بدرود',
  'khosh amadid': 'خوش آمدید',
  'sobh bekheyr': 'صبح بخیر',
  'shab bekheyr': 'شب بخیر',
  'chetori': 'چطوری',
  'khubi': 'خوبی',
  'chetorid': 'چطورید',
  'khubin': 'خوبین',
  
  // Common pronouns
  'man': 'من',
  'to': 'تو',
  'shoma': 'شما',
  'ma': 'ما',
  'anha': 'آنها',
  'ou': 'او',
  
  // Common verbs
  'hastam': 'هستم',
  'hasti': 'هستی',
  'ast': 'است',
  'hastid': 'هستید',
  'hastand': 'هستند',
  'raft': 'رفت',
  'amad': 'آمد',
  'migam': 'میگم',
  'migi': 'میگی',
  'mige': 'میگه',
  
  // Common adjectives
  'khoob': 'خوب',
  'bad': 'بد',
  'ziba': 'زیبا',
  'bozorg': 'بزرگ',
  'koochak': 'کوچک',
  'sard': 'سرد',
  'garm': 'گرم',
  
  // Common nouns
  'ketab': 'کتاب',
  'khane': 'خانه',
  'mashin': 'ماشین',
  'doost': 'دوست',
  'gol': 'گل',
  'ab': 'آب',
  'nan': 'نان',
  
  // Time-related words
  'emrooz': 'امروز',
  'farda': 'فردا',
  'dirooz': 'دیروز',
  'alan': 'الان',
  'hala': 'حالا',
  'sob': 'صبح',
  'zohr': 'ظهر',
  'shab': 'شب',
  
  // Question words
  'chi': 'چی',
  'koja': 'کجا',
  'key': 'کی',
  'chera': 'چرا',
  'chetor': 'چطور',
  
  // Common expressions
  'merci': 'مرسی',
  'mamnoon': 'ممنون',
  'motshakeram': 'متشکرم',
  'khahesh mikonam': 'خواهش میکنم',
  'bebakhshid': 'ببخشید',
  'lotfan': 'لطفاً',
  
  // Numbers
  'yek': 'یک',
  'do': 'دو',
  'se': 'سه',
  'chahar': 'چهار',
  'panj': 'پنج',
  'shish': 'شش',
  'haft': 'هفت',
  'hasht': 'هشت',
  'noh': 'نه',
  'dah': 'ده',
  
  // Family terms
  'pedar': 'پدر',
  'madar': 'مادر',
  'khahar': 'خواهر',
  'baradar': 'برادر',
  'amoo': 'عمو',
  'khale': 'خاله',
  'dayi': 'دایی',
  'ame': 'عمه',
  
  // Extended dictionary - Expanded vocabulary
  'mamnoonam': 'ممنونم',
  'khaste nabashid': 'خسته نباشید',
  'khoosh ghalb': 'خوش قلب',
  'eshgh': 'عشق',
  'delam barat tang shode': 'دلم برات تنگ شده',
  'doset daram': 'دوستت دارم',
  'ghabel nadare': 'قابل نداره',
  'chashm': 'چشم',
  'bashe': 'باشه',
  'hatman': 'حتما',
  'aslan': 'اصلا',
  'faghat': 'فقط',
  'midonam': 'میدونم',
  'nemidonam': 'نمیدونم',
  'fekr mikonam': 'فکر میکنم',
  'komak': 'کمک',
  'chera ke na': 'چرا که نه',
  'cheghadr': 'چقدر',
  'khaste': 'خسته',
  'gorosne': 'گرسنه',
  'teshne': 'تشنه',
  
  // Food related
  'ghaza': 'غذا',
  'noon': 'نان',
  'berenj': 'برنج',
  'morgh': 'مرغ',
  'goosht': 'گوشت',
  'sabzi': 'سبزی',
  'mive': 'میوه',
  'chai': 'چای',
  'ghahve': 'قهوه',
  'shir': 'شیر',
  'ab': 'آب',
  'abmive': 'آبمیوه',
  
  // Places
  'madrese': 'مدرسه',
  'daneshgah': 'دانشگاه',
  'edare': 'اداره',
  'khiyaban': 'خیابان',
  'park': 'پارک',
  'bazar': 'بازار',
  'hospital': 'بیمارستان',
  'restoran': 'رستوران',
  'hotel': 'هتل',
  'foroodgah': 'فرودگاه',
  'sahel': 'ساحل',
  'kharid': 'خرید',
  
  // Professions
  'moalem': 'معلم',
  'doktor': 'دکتر',
  'mohandes': 'مهندس',
  'karmand': 'کارمند',
  'forooshande': 'فروشنده',
  'raanande': 'راننده',
  'vakil': 'وکیل',
  'kargard': 'کارگردان',
  'honarpishe': 'هنرپیشه',
  'khabar negar': 'خبرنگار',
  
  // Technology terms
  'computer': 'کامپیوتر',
  'internet': 'اینترنت',
  'mobile': 'موبایل',
  'website': 'وبسایت',
  'app': 'اپلیکیشن',
  'email': 'ایمیل',
  'safhe': 'صفحه',
  'danlod': 'دانلود',
  'file': 'فایل',
  'program': 'برنامه',
  'bazi': 'بازی',
  
  // Academic terms
  'ketab': 'کتاب',
  'daneshjo': 'دانشجو',
  'ostad': 'استاد',
  'emtehan': 'امتحان',
  'nomre': 'نمره',
  'kelas': 'کلاس',
  'tadris': 'تدریس',
  'tahsil': 'تحصیل',
  'madrak': 'مدرک',
  'reshte': 'رشته',
  'daneshkade': 'دانشکده',
  
  // Feelings and emotions
  'khoshhal': 'خوشحال',
  'narahat': 'ناراحت',
  'asabani': 'عصبانی',
  'khooshhal': 'خوشحال',
  'ghamgin': 'غمگین',
  'heyejan zade': 'هیجان‌زده',
  'khaste': 'خسته',
  'aramesh': 'آرامش',
  'stress': 'استرس',
  'eshgh': 'عشق',
  'nefrat': 'نفرت',
  
  // Nature
  'derakht': 'درخت',
  'gol': 'گل',
  'jangal': 'جنگل',
  'kuh': 'کوه',
  'darya': 'دریا',
  'sahel': 'ساحل',
  'asman': 'آسمان',
  'khorshid': 'خورشید',
  'mah': 'ماه',
  'setare': 'ستاره',
  'barf': 'برف',
  'baran': 'باران',
  'abr': 'ابر',

  // Common phrases in conversations
  'che khabar': 'چه خبر',
  'halet chetore': 'حالت چطوره',
  'khoob hastam': 'خوب هستم',
  'mamnoon az shoma': 'ممنون از شما',
  'khahesh mikonam': 'خواهش می‌کنم',
  'bebakhshid': 'ببخشید',
  'eshtebah kardam': 'اشتباه کردم',
  'fekr mikonam ke': 'فکر می‌کنم که',
  'nazare shoma chist': 'نظر شما چیست',
  'movafegham': 'موافقم',
  'mokhalefam': 'مخالفم',
  'omidvaram': 'امیدوارم',
  
  // Calendar and time
  'sal': 'سال',
  'mah': 'ماه',
  'hafte': 'هفته',
  'rooz': 'روز',
  'saat': 'ساعت',
  'daghighe': 'دقیقه',
  'saniye': 'ثانیه',
  'shanbe': 'شنبه',
  'yekshanbe': 'یکشنبه',
  'doshanbe': 'دوشنبه',
  'seshanbe': 'سه‌شنبه',
  'chaharshanbe': 'چهارشنبه',
  'panjshanbe': 'پنجشنبه',
  'jome': 'جمعه',
  'norooz': 'نوروز',
  
  // Colors
  'sefid': 'سفید',
  'siah': 'سیاه',
  'ghermez': 'قرمز',
  'abi': 'آبی',
  'sabz': 'سبز',
  'zard': 'زرد',
  'narenji': 'نارنجی',
  'banafsh': 'بنفش',
  'khakestari': 'خاکستری',
  'ghahveyi': 'قهوه‌ای',
  'sorati': 'صورتی',
  'talayi': 'طلایی',
  
  // Housing and furniture
  'khane': 'خانه',
  'apartment': 'آپارتمان',
  'otagh': 'اتاق',
  'ashpazkhane': 'آشپزخانه',
  'hamam': 'حمام',
  'dastshooyi': 'دستشویی',
  'miz': 'میز',
  'sandali': 'صندلی',
  'takht': 'تخت',
  'komod': 'کمد',
  'parde': 'پرده',
  'farsh': 'فرش',
  
  // Transportation
  'mashin': 'ماشین',
  'autobus': 'اتوبوس',
  'taxi': 'تاکسی',
  'metro': 'مترو',
  'havapeima': 'هواپیما',
  'ghatar': 'قطار',
  'kashti': 'کشتی',
  'docharkheh': 'دوچرخه',
  'motor': 'موتور',
  'piyade': 'پیاده',
  
  // Common actions
  'raftan': 'رفتن',
  'amadan': 'آمدن',
  'khordan': 'خوردن',
  'khandan': 'خواندن',
  'neveshtan': 'نوشتن',
  'didian': 'دیدن',
  'shenidan': 'شنیدن',
  'khabidan': 'خوابیدن',
  'david': 'دوید',
  'kharid': 'خرید',
  'foroosh': 'فروش',
  'baz kardan': 'باز کردن',
  'bastan': 'بستن',
  'shostam': 'شستن',
  'miram': 'می‌رم',
  'miay': 'می‌آی',
  'mire': 'می‌ره'
};
