export type ToolType = 'text' | 'image' | 'random-password' | 'prime-checker' | 'calculator' | 'seo' | 'random' | 'number' | 'investment-calculator' | 'mortgage-calculator' | 'today-date' | 'date-difference' | 'world-time' | 'profit' | 'scientific-calculator' | 'rent-factors';

export const toolTypeBySlug: Record<string, ToolType> = {
  // Text tools
  'latin-to-persian-convertor': 'text',
  'text-counter': 'text',
  'text-reverse': 'text',
  'remove-duplicate-lines': 'text',
  'text-sorter': 'text',
  'text-trimmer': 'text',
  'remove-empty-lines': 'text',
  'emoji-remover': 'text',
  'slug-generator': 'text',
  'text-uppercasing': 'text',
  'text-lowercasing': 'text',
  'text-titlecase': 'text',
  'uppercase-finder': 'text',
  'character-remover': 'text',
  'word-replacer': 'text',
  'random-paragraph-generator': 'text',
  'capitalize-tool': 'text',
  'advanced-text-analyzer': 'text',
  'bulk-slug-generator': 'text',
  'filter-lines-tool': 'text',
  'emoji-text-inserter': 'text',
  'remove-html-tags': 'text',
  'mirror-text': 'text',
  'special-character-finder': 'text',
  'remove-accent-tool': 'text',
  // New Persian Text Tools
  'persian-half-space-corrector': 'text',
  'persian-keyboard-converter': 'text',
  'persian-number-converter': 'text',
  'persian-text-standardizer': 'text',
  
  // image tools
  'image-compressor': 'image',
  'image-resizer': 'image',
  'image-to-webp': 'image',
  'image-to-jpg': 'image',
  'image-to-png': 'image',
  'image-rotate': 'image',
  'image-flip': 'image',
  'image-grayscale': 'image',
  'image-blur': 'image',
  'image-cropper': 'image',
  'image-editor': 'image',
  'remove-bg': 'image',
  'image-pixelator': 'image',
  'image-sepia': 'image',
  'photo-dimensions-finder': 'image',
  'batch-image-converter': 'image',
  'svg-to-png-converter': 'image',
  
  // Special tools
  'random-password': 'random-password',
  'prime-checker': 'prime-checker',
  'percentage-calculator': 'calculator',
  'loan-calculator': 'calculator',
  'age-calculator': 'calculator',
  'bmi-calculator': 'calculator',
  'salary-tax-calculator': 'calculator',
  'discount-calculator': 'calculator',
  'unit-converter': 'calculator',
  'currency-converter': 'calculator',
  'date-difference': 'calculator',
  'tip-calculator': 'calculator',
  'area-calculator': 'calculator',
  'volume-calculator': 'calculator',
  'font-size-calculator': 'calculator',
  'range-calculator': 'calculator',
  'unit-list-generator': 'calculator',
  'investment-calculator': 'investment-calculator',
  'mortgage-calculator': 'mortgage-calculator',
  'today-date-converter': 'today-date',
  'date-difference-calculator': 'date-difference',
  'world-time-converter': 'world-time',
  'profit-calculator': 'profit',
  'scientific-calculator': 'scientific-calculator',
  'rent-factors-calculator': 'rent-factors',

  // SEO tools
  'meta-tag-generator': 'seo',
  'robots-txt-generator': 'seo',
  'utm-builder': 'seo',
  'keyword-density': 'seo',
  'open-graph-generator': 'seo',
  'sitemap-generator': 'seo',
  'favicon-generator': 'seo',
  'page-title-check': 'seo',
  'canonical-check': 'seo',
  'alt-text-analyzer': 'seo',
  'friendly-url-checker': 'seo',
  'heading-structure-checker': 'seo',
  'seo-title-case': 'seo',
  'auto-shorten-link': 'seo',
  'meta-description-suggester': 'seo',
  'alt-attribute-generator': 'seo',
  'bulk-url-checker': 'seo',
  'seo-redirect-generator': 'seo',
  'meta-viewport-checker': 'seo',
  'html-heading-extractor': 'seo',
  'html-lang-checker': 'seo',
  'schema-generator': 'seo',
  'meta-refresh-generator': 'seo',
  'social-tags-generator': 'seo',
  'meta-keywords-extractor': 'seo',
  
  // Random tools
  'random-color-generator': 'random',
  'random-string': 'random',
  'random-date': 'random',
  'random-number': 'random',
  'coin-flip': 'random',
  'random-picker': 'random',
  'random-emoji-generator': 'random',
  'random-word-generator': 'random',
  'dice-roller': 'random',
  'random-user-generator': 'random',
  'random-quote-generator': 'random',
  'random-qrcode-generator': 'random',
  'password-strength-check': 'random',
  'random-username-generator': 'random',
  
  // Number tools
  'number-converter': 'number',
  'roman-numeral-converter': 'number',
  'number-formatter': 'number',
  'number-rounder': 'number',
  'decimal-binary-converter': 'number',
  'decimal-hex-converter': 'number',
  'decimal-octal-converter': 'number',
  'even-odd-checker': 'number',
  'sum-calculator': 'number',
  'random-number-picker': 'number',
  'fibonacci-finder': 'number',
  'even-number-list': 'number',
  'odd-number-list': 'number',
  'decimal-to-roman': 'number',
  'number-shuffler': 'number',
  'number-comparator': 'number',
  'duplicate-number-finder': 'number',
};
