
import React, { useState } from 'react';
import { tools } from '@/data/tools';
import { ToolInfoCard } from '@/components/ToolInfoCard';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from 'sonner';
import { Code, Filter, Hash } from 'lucide-react';
import { copyToClipboard } from '@/utils/randomUtils';

interface SeoToolProps {
  slug: string;
}

export default function SeoTool({ slug }: SeoToolProps) {
  const toolMeta = tools.find((t) => t.slug === slug);
  
  const [title, setTitle] = useState<string>('');
  const [description, setDescription] = useState<string>('');
  const [keywords, setKeywords] = useState<string>('');
  const [url, setUrl] = useState<string>('');
  const [author, setAuthor] = useState<string>('');
  const [metaTagsOutput, setMetaTagsOutput] = useState<string>('');
  
  const [userAgent, setUserAgent] = useState<string>('*');
  const [allowPaths, setAllowPaths] = useState<string>('/');
  const [disallowPaths, setDisallowPaths] = useState<string>('');
  const [sitemapUrl, setSitemapUrl] = useState<string>('');
  const [robotsTxtOutput, setRobotsTxtOutput] = useState<string>('');
  
  const [keywordText, setKeywordText] = useState<string>('');
  const [targetKeyword, setTargetKeyword] = useState<string>('');
  const [keywordDensityResult, setKeywordDensityResult] = useState<{
    totalWords: number;
    keywordCount: number;
    density: number;
  } | null>(null);

  const generateMetaTags = () => {
    let metaTags = `<!-- Meta Tags Generated by SEO Tool -->\n`;
    metaTags += `<title>${title}</title>\n`;
    
    if (description) {
      metaTags += `<meta name="description" content="${description}" />\n`;
    }
    
    if (keywords) {
      metaTags += `<meta name="keywords" content="${keywords}" />\n`;
    }
    
    if (author) {
      metaTags += `<meta name="author" content="${author}" />\n`;
    }
    
    metaTags += `<meta property="og:title" content="${title}" />\n`;
    
    if (description) {
      metaTags += `<meta property="og:description" content="${description}" />\n`;
    }
    
    if (url) {
      metaTags += `<meta property="og:url" content="${url}" />\n`;
    }
    
    metaTags += `<meta name="twitter:card" content="summary_large_image" />\n`;
    metaTags += `<meta name="twitter:title" content="${title}" />\n`;
    
    if (description) {
      metaTags += `<meta name="twitter:description" content="${description}" />\n`;
    }
    
    metaTags += `<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n`;
    
    setMetaTagsOutput(metaTags);
    toast.success("متا تگ‌ها با موفقیت ایجاد شدند");
  };

  const generateRobotsTxt = () => {
    let robotsTxt = `# robots.txt generated by SEO Tool\n\n`;
    robotsTxt += `User-agent: ${userAgent}\n`;
    
    if (allowPaths) {
      const paths = allowPaths.split('\n');
      paths.forEach(path => {
        if (path.trim()) {
          robotsTxt += `Allow: ${path.trim()}\n`;
        }
      });
    }
    
    if (disallowPaths) {
      const paths = disallowPaths.split('\n');
      paths.forEach(path => {
        if (path.trim()) {
          robotsTxt += `Disallow: ${path.trim()}\n`;
        }
      });
    }
    
    if (sitemapUrl) {
      robotsTxt += `\nSitemap: ${sitemapUrl}\n`;
    }
    
    setRobotsTxtOutput(robotsTxt);
    toast.success("فایل robots.txt با موفقیت ایجاد شد");
  };

  const calculateKeywordDensity = () => {
    if (!keywordText || !targetKeyword) {
      toast.error("لطفاً متن و کلمه کلیدی را وارد کنید");
      return;
    }
    
    const words = keywordText.toLowerCase().split(/\s+/).filter(word => word.length > 0);
    const totalWords = words.length;
    
    const keyword = targetKeyword.toLowerCase();
    const keywordCount = words.filter(word => word === keyword).length;
    
    const density = totalWords > 0 ? (keywordCount / totalWords) * 100 : 0;
    
    setKeywordDensityResult({
      totalWords,
      keywordCount,
      density: parseFloat(density.toFixed(2))
    });
    
    toast.success("چگالی کلمه کلیدی محاسبه شد");
  };

  if (!toolMeta) return null;

  return (
    <div className="space-y-6">
      <ToolInfoCard
        name={toolMeta.name}
        description={toolMeta.description}
        learnMoreUrl={`https://www.google.com/search?q=${encodeURIComponent(toolMeta.name)}`}
      />
      
      {slug === 'meta-tag-generator' ? (
        <Card>
          <CardContent className="p-6 space-y-4">
            <div className="space-y-2">
              <Input
                placeholder="عنوان صفحه"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
              <Textarea
                placeholder="توضیحات متا"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
              <Input
                placeholder="کلمات کلیدی (با کاما جدا کنید)"
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
              />
              <Input
                placeholder="آدرس URL"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
              />
              <Input
                placeholder="نویسنده"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
              />
              <Button 
                onClick={generateMetaTags}
                className="w-full"
              >
                <Code className="mr-2" size={18} />
                تولید متا تگ‌ها
              </Button>
            </div>
            
            {metaTagsOutput && (
              <div 
                className="p-4 bg-muted rounded-lg cursor-pointer font-mono text-sm whitespace-pre-wrap dir-ltr"
                onClick={() => copyToClipboard(metaTagsOutput)}
              >
                {metaTagsOutput}
              </div>
            )}
          </CardContent>
        </Card>
      ) : slug === 'robots-txt-generator' ? (
        <Card>
          <CardContent className="p-6 space-y-4">
            <div className="space-y-2">
              <Select value={userAgent} onValueChange={setUserAgent}>
                <SelectTrigger>
                  <SelectValue placeholder="User-agent" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="*">همه روبات‌ها (*)</SelectItem>
                  <SelectItem value="Googlebot">Googlebot</SelectItem>
                  <SelectItem value="Bingbot">Bingbot</SelectItem>
                  <SelectItem value="Baiduspider">Baiduspider</SelectItem>
                  <SelectItem value="YandexBot">YandexBot</SelectItem>
                </SelectContent>
              </Select>
              
              <Textarea
                placeholder="مسیرهای مجاز (هر مسیر در یک خط)"
                value={allowPaths}
                onChange={(e) => setAllowPaths(e.target.value)}
              />
              
              <Textarea
                placeholder="مسیرهای غیر مجاز (هر مسیر در یک خط)"
                value={disallowPaths}
                onChange={(e) => setDisallowPaths(e.target.value)}
              />
              
              <Input
                placeholder="آدرس نقشه سایت (Sitemap)"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
              />
              
              <Button 
                onClick={generateRobotsTxt}
                className="w-full"
              >
                <Code className="mr-2" size={18} />
                تولید robots.txt
              </Button>
            </div>
            
            {robotsTxtOutput && (
              <div 
                className="p-4 bg-muted rounded-lg cursor-pointer font-mono text-sm whitespace-pre-wrap dir-ltr"
                onClick={() => copyToClipboard(robotsTxtOutput)}
              >
                {robotsTxtOutput}
              </div>
            )}
          </CardContent>
        </Card>
      ) : slug === 'keyword-density' ? (
        <Card>
          <CardContent className="p-6 space-y-4">
            <div className="space-y-2">
              <Textarea
                placeholder="متن مورد نظر را وارد کنید"
                value={keywordText}
                onChange={(e) => setKeywordText(e.target.value)}
                className="min-h-32"
              />
              
              <Input
                placeholder="کلمه کلیدی هدف"
                value={targetKeyword}
                onChange={(e) => setTargetKeyword(e.target.value)}
              />
              
              <Button 
                onClick={calculateKeywordDensity}
                className="w-full"
              >
                <Filter className="mr-2" size={18} />
                محاسبه چگالی کلمه کلیدی
              </Button>
            </div>
            
            {keywordDensityResult && (
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <div className="flex justify-between">
                  <span>تعداد کل کلمات:</span>
                  <span className="font-bold">{keywordDensityResult.totalWords}</span>
                </div>
                <div className="flex justify-between">
                  <span>تعداد تکرار کلمه کلیدی:</span>
                  <span className="font-bold">{keywordDensityResult.keywordCount}</span>
                </div>
                <div className="flex justify-between">
                  <span>چگالی کلمه کلیدی:</span>
                  <span className="font-bold">{keywordDensityResult.density}%</span>
                </div>
                <div className="mt-4 text-sm text-gray-500">
                  {keywordDensityResult.density < 1 ? (
                    "چگالی کلمه کلیدی کم است. برای بهبود سئو، استفاده بیشتری از کلمه کلیدی توصیه می‌شود."
                  ) : keywordDensityResult.density > 5 ? (
                    "چگالی کلمه کلیدی زیاد است. این ممکن است به عنوان اسپم تلقی شود."
                  ) : (
                    "چگالی کلمه کلیدی در محدوده مناسب قرار دارد (بین 1% تا 5%)."
                  )}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      ) : (
        <div className="rounded-lg border p-6 shadow-sm">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <h3 className="text-lg font-medium">این ابزار در حال توسعه است</h3>
            <p className="text-muted-foreground">
              این ابزار به زودی راه‌اندازی خواهد شد. لطفاً بعداً مراجعه کنید.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
